CC = gcc
AR = ar
W = -W -Wall -Wno-unused-parameter -Wbad-function-cast -Wuninitialized
THREADS = -pthread
OPT = -O2 -g
CFLAGS = $(THREADS) $(OPT) $(W)
SOEXT = .so
prefix = build
srcdir = lib/liblmdb
bindir = $(prefix)/bin
libdir = $(prefix)/lib
objdir = ${prefix}/obj
includedir = $(prefix)/include

########################################################################

IHDRS = lmdb.h
ILIBS = liblmdb.a liblmdb$(SOEXT)
IPROGS = mdb_stat mdb_copy mdb_dump mdb_load mdb_drop

HDRS = $(foreach hdr,$(IHDRS),$(includedir)/$(hdr))
SRCS = $(wildcard *.c $(foreach fd, $(srcdir), $(fd)/*.c)) 
NODIR_SRC = $(notdir $(SRCS))
OBJS = $(addprefix ${objdir}/, $(NODIR_SRC:c=o)) # .build/xxx.o
LIBS = $(foreach lib,$(ILIBS),$(libdir)/$(lib))
PROGS = $(foreach prog,$(IPROGS),$(bindir)/$(prog))
INC_DIRS = -I./ $(addprefix -I, $(srcdir))

all: $(HDRS) $(OBJS) $(LIBS) $(PROGS)

.PHONY: echo

echo:
	@echo "HDRS: $(HDRS)"
	@echo "SRCS: $(SRCS)"
	@echo "NODIR_SRC: $(NODIR_SRC)"
	@echo "OBJS: $(OBJS)"
	@echo "LIBS: $(LIBS)"
	@echo "PROGS: $(PROGS)"

prep:
	mkdir -p $(bindir)
	mkdir -p $(libdir)
	mkdir -p $(objdir)

clean:
	rm -rf $(bindir)/* $(objdir)/* $(libdir)/* $(includedir)/*

$(libdir)/liblmdb.a: $(objdir)/mdb.o $(objdir)/midl.o
	mkdir -p $(libdir)
	$(AR) rs $@ $(objdir)/mdb.o $(objdir)/midl.o

$(libdir)/liblmdb$(SOEXT): $(objdir)/mdb.lo $(objdir)/midl.lo
	$(CC) -pthread -shared -o $@ $(objdir)/mdb.lo $(objdir)/midl.lo

$(bindir)/mdb_stat: $(objdir)/mdb_stat.o $(libdir)/liblmdb.a
$(bindir)/mdb_copy: $(objdir)/mdb_copy.o $(libdir)/liblmdb.a
$(bindir)/mdb_dump: $(objdir)/mdb_dump.o $(libdir)/liblmdb.a
$(bindir)/mdb_load: $(objdir)/mdb_load.o $(libdir)/liblmdb.a
$(bindir)/mdb_drop: $(objdir)/mdb_drop.o $(libdir)/liblmdb.a

$(bindir)/%: $(objdir)/%.o $(LIBS)
	mkdir -p $(@D)
	$(CC) $(CFLAGS) $^ -o $@

$(includedir)/%.h:
	mkdir -p $(@D)
	cp $(srcdir)/$(notdir $@) $@

$(objdir)/%.o: $(srcdir)/%.c $(HDRS)
	mkdir -p $(@D)
	$(CC) $(CFLAGS) -c $< -o $@ $(INC_DIRS)

$(objdir)/%.lo: $(srcdir)/%.c $(HDRS)
	mkdir -p $(@D)
	$(CC) $(CFLAGS) -fPIC -c $< -o $@ $(INC_DIRS)

# ------- AWM ------
.PHONY += awm
awm: $(bindir)/awm

$(bindir)/awm: $(objdir)/awm.o $(LIBS)
	mkdir -p .testdb
	mkdir -p $(@D)
	$(CC) $(CFLAGS) $^ -o $@

$(objdir)/awm.o: src/awm.c $(HDRS)
	mkdir -p $(@D)
	$(CC) $(CFLAGS) -c $< -o $@ $(INC_DIRS)

# ------ LMDB-FFI ------
.PHONY += lmdb-ffi

lmdb-ffi: $(bindir)/lmdb-ffi $(libdir)/liblmdb-ffi$(SOEXT)

$(bindir)/lmdb-ffi: $(objdir)/lmdb-ffi.o $(LIBS)
	mkdir -p .testdb
	mkdir -p $(@D)
	$(CC) $(CFLAGS) $^ -o $@

$(libdir)/liblmdb-ffi$(SOEXT): $(objdir)/lmdb-ffi.o $(LIBS)
	$(CC) $(CFLAGS) -pthread -shared -o $@ $< $(objdir)/mdb.lo $(objdir)/midl.lo

$(objdir)/lmdb-ffi.o: src/lmdb-ffi.c $(HDRS)
	mkdir -p $(@D)
	$(CC) $(CFLAGS) -fPIC -c $< -o $@ $(INC_DIRS)